name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v1.4
        with:
          host-url: http://localhost:9000
          login: ${{ secrets.SONAR_TOKEN }}
